services:
  srv-grafana:
    image: grafana/grafana:${RELEASE}
    env_file:
      - .env
    container_name: ${SRV_GRAFANA_HOST}
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASSWD}
      GF_DATABASE_TYPE: ${DATABASE_TYPE}
      GF_DATABASE_HOST: ${DATABASE_HOST}
      GF_DATABASE_NAME: ${DATABASE_NAME}
      GF_DATABASE_USER: ${DATABASE_USER}
      GF_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${PORTS}
    networks:
      network-share:
        ipv4_address: ${IPV4_ADDRESS}
    volumes:
      - ${VOL_GRAFANA_PATH}
      # Descomente a linha abaixo apos copiar os arquivos grafana.ini e ldap.toml para a pasta config
      #- ${VOL_CONFIG_PATH}
      - ${VOL_MAPS_PATH}
      - ${VOL_LOCALTIME}
      - ${VOL_TZ}
    restart: unless-stopped

networks:
  network-share:
    external: true
    ipam:
      config:
        - subnet: ${SUBNET}
